"""The agent's field types must not fall behind the builder's, silently.

On 2026-09-25 a user asked for tabs and a stepper and was told: "I can't add Tabs or Stepper
components here. The builder only has basic field types, with no layout containers like tabs or
panels and no dedicated stepper control." Every part of that was false about the builder. The
palette had all of them — `stepper` had shipped hours earlier — and the agent's own list held 13
of form-core's 48. It described its own gap as the product's limit, and then, pressed, invented
an explanation of what Stepper and Tabs are.

Nothing connected the two lists, so the gap could only widen. This is the connection: every type
form-core offers must be either SUPPORTED here or listed in NOT_SUPPORTED with a reason. A new
field type in form-core fails this test until someone decides which it is.

The fixture is generated by luke-forms (`npm run fixtures:field-types`) and copied in, mirroring
`agent-schema-cases.json`, which travels the other way.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import get_args

import pytest

from luke_agents.agents.form_agent.schema import CONTAINER_TYPES, FieldType

FIXTURE = Path(__file__).parent / "fixtures" / "field-types.json"


#: Types form-core offers that the agent deliberately does NOT emit. The reason is the point:
#: an entry here is a decision, and an unexplained one is indistinguishable from an oversight.
NOT_SUPPORTED: dict[str, str] = {
    "address": "superseded by addressBlock, which the agent does emit; two address types in the "
               "prompt only invites the model to pick the worse one",
    "tagsField": "legacy alias of `tags`",
    "array": "a repeating group with no visual of its own — needs the nesting story editGrid has, "
             "and an LLM has no way to know how many rows are meant",
    "map": "needs a geo provider configured per form; an agent adding one silently produces a "
           "field that cannot render",
    "payment": "server-authoritative pricing and a per-form Stripe Connect account. A model "
               "adding a charge to someone's form is not a thing that should be one sentence away",
    "dataGrid": "row-schema container: its children are a COLUMN template, not a section, so it "
                "does not fit the children model below",
    "editGrid": "same as dataGrid — a row template rather than a layout box",
    "container": "a generic grouping box with no visual identity; panel/fieldset/well cover every "
                 "case a person would ask for by name",
    "html": "raw author HTML. The agent writes from user text, and user text becoming HTML in a "
            "published form is an injection surface, sanitiser or no sanitiser",
    "htmlElement": "same as html",
    "hr": "alias of divider",
}


def _fixture() -> dict:
    assert FIXTURE.exists(), (
        f"{FIXTURE} is missing. Generate it in luke-forms with `npm run fixtures:field-types` "
        "and copy it here."
    )
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def _supported() -> set[str]:
    return set(get_args(FieldType))


def test_every_builder_type_is_supported_or_explained():
    """The guard. A type form-core grew is a decision to take, not a silence to keep."""
    offered = {t["name"] for t in _fixture()["types"]}
    unaccounted = sorted(offered - _supported() - set(NOT_SUPPORTED))
    assert not unaccounted, (
        "form-core offers field types the agent neither emits nor declines:\n  "
        + "\n  ".join(unaccounted)
        + "\n\nAdd each to FieldType in luke_agents/agents/form_agent/schema.py (and teach the "
        "prompt when to use it), or to NOT_SUPPORTED above WITH A REASON. Leaving it out is how "
        "the agent ends up telling someone the builder cannot do what the builder plainly does."
    )


def test_the_agent_never_emits_a_type_the_builder_does_not_have():
    """The other direction: a type the agent invents is rejected at publish, after the person has
    already been told it was added."""
    offered = {t["name"] for t in _fixture()["types"]}
    phantom = sorted(_supported() - offered)
    assert not phantom, f"agent emits types form-core does not know: {phantom}"


def test_exclusions_are_real_types_and_not_stale():
    """An exclusion for a type that no longer exists is a comment pretending to be a decision."""
    offered = {t["name"] for t in _fixture()["types"]}
    stale = sorted(set(NOT_SUPPORTED) - offered)
    assert not stale, f"NOT_SUPPORTED names types form-core no longer has: {stale}"
    overlap = sorted(set(NOT_SUPPORTED) & _supported())
    assert not overlap, f"listed as both supported and not supported: {overlap}"


@pytest.mark.parametrize("name", ["stepper", "tabs", "panel", "rating", "signature", "file"])
def test_the_types_the_user_was_told_did_not_exist(name):
    """Named individually because these are the ones that produced the false answer."""
    assert name in _supported(), f"{name} must be emittable — the palette has had it all along"


def test_containers_are_marked_as_containers_in_the_fixture_too():
    """CONTAINER_TYPES drives whether `children` is allowed on a field. If it disagreed with
    form-core, the agent would either refuse to nest something that nests, or nest something that
    does not — and a child whose parent cannot hold it is a schema that fails validation."""
    by_name = {t["name"]: t for t in _fixture()["types"]}
    for name in CONTAINER_TYPES:
        assert name in by_name, f"{name} is not a form-core type at all"
        assert by_name[name]["isContainer"], f"{name} is not a container in form-core"
    # And every container the agent supports is declared as one here.
    for name in _supported():
        if by_name[name]["isContainer"]:
            assert name in CONTAINER_TYPES, (
                f"{name} is a container in form-core but not in CONTAINER_TYPES, so the agent "
                "would emit it as a leaf and its children would be lost"
            )
